name: build_push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: suisei-cn/actions-download-file@v1
      id: downloadboost
      name: Download Boost
      with:
        url: "https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.7z"
        target: Thirdparty/

    - uses: suisei-cn/actions-download-file@v1
      id: downloadicu
      name: Download Icu
      with:
        url: "https://github.com/unicode-org/icu/releases/download/release-60-3/icu4c-60_3-src.zip"
        target: Thirdparty/

#    - name: Extract Zip files
#      run: |
#        7z e ./Thirdparty/boost_1_73_0.7z -oThirdparty/Boost
#        7z e ./Thirdparty/icu4c-60_3-src.zip -oThirdparty/Icu

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          make
          diffutils
          yasm
          nasm   

    - shell: msys2 {0}
      run: mv ~/usr/bin/link.exe ~/usr/bin/link.exe.bak

    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg
    
    - run: c:/ffmpeg/configure --toolchain=msvc --enable-gpl --enable-version3 --disable-encoders --disable-programs --disable-filters --disable-network --disable-doc --disable-avdevice --disable-postproc --disable-avfilter --enable-dxva2 --enable-d3d11va

    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.6

    - shell: msys2 {0}
      run: |
        make
        make install
