name: build_push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: suisei-cn/actions-download-file@v1
      id: downloadboost
      name: Download Boost
      with:
        url: "https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.7z"
        target: Thirdparty/

    - uses: suisei-cn/actions-download-file@v1
      id: downloadicu
      name: Download Icu
      with:
        url: "https://github.com/unicode-org/icu/releases/download/release-60-3/icu4c-60_3-src.zip"
        target: Thirdparty/

    - name: Extract Boost files
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq ./Thirdparty/boost_1_73_0.7z -d ./Thirdparty/Boost
    - name: Extract Icu files
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq ./Thirdparty/icu4c-60_3-src.zip -d ./Thirdparty/Icu

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          make
          diffutils
          yasm
          nasm   

    - shell: msys2 {0}
      run: mv /usr/bin/link.exe /usr/bin/link.exe.bak

    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg

    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.6

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app
      run: msbuild Kainote/Kainote.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
